add Invoice task 1
pswientek/invoicing-system-piotr-swientek pull request #1
Opened 2022-05-16 21:38 UTC by pswientek

2022-05-19 12:04 UTC, radoslawdabrowski requested changes

2022-05-19 12:04 UTC, radoslawdabrowski commented on .gitignore
> +*.iml
add .idea directory to .gitignore

2022-05-20 08:35 UTC, AdamLudzia approved these changes
wydaje mi się, że jest ok :)

2022-05-23 06:06 UTC, radoslawdabrowski approved these changes

2022-05-26 19:40 UTC, merged